sudo: required
dist: trusty
os: osx
osx_image: xcode9.4
language: node_js
node_js:
- 8.9.4
before_deploy:
 - brew update
 - brew upgrade
 - brew install Caskroom/cask/xquartz
 - brew install wine
 - brew install mono
 - brew install gnu-tar graphicsmagick xz
 - brew install rpm
 - brew install snapcraft
 - npm install -g electron-packager
deploy:
 - provider: script
   script: ./bin/create_tag.sh
   skip_cleanup: true
   on:
     branch: master
 - provider: script
   script: ./bin/package_app.sh
   skip_cleanup: true
   on:
     tags: true
 - provider: releases
   api_key:
     secure: "XjI4/LyB5/3ZkrLJV6fTBBmuBRKzOLQwUMIL7BdEmJMajEc24roROuzZIXK9rTDBqHFkTQr/bsKmYzUXQKaOXLCFLez1g/Fn0obLTDEIXN0Bsk7Is0MzyE0qoGo7RKK/ut8C/EfuqUEV09vq6aD6AiNDZ+VrGQcXkDEamPk5kEB5YMj83SiqBx4+ohQky59vSPJAYGy/Q/63B1ShhUghpnHRLP4TBkBGJBgNyCO68Pgj+glAZMtw3w7g2+SKntXbWgTv8fSce7Li6Zva8E+2bH5qAPN3P7aInkYXPkyZHH6CmkTeGG5IdmJhoL8+jkU9h4M2tYudezzyMajto41JJa5JbFG73wVr1vpF7XhiWvuHpNWhJTIo9DwR5IYKJm5ZQZNVWjy5ZfvjUQs5cyzz9dgPhTLuDDr39Kpsb9O3kSevGaiCnxGJvsviqcoKTSeD2YyQxnV9Q7yvoGD5lNJfK7IeIFprzWGDjDFxGy0f28nn4uGdvS8M6Kw5osTZwkOvkAD3+S2lLDK2kqqpX6eREp3IE71iongdwalilwRoBV6oEDMsm3pZJHmP3QMw5c74ql65c7YAl+poYziFJY8cBU/Kc4Lx/NoDVxgo6D8KMBGPUEWxxfqTbAOrYni5G62OCBNuD3ALuaQAsLfi6J3Zt0OF+SMaMNzfsL7/vCZrX5s="
   file:
     - dist/aux-app.dmg
     - dist/aux-app.setup.exe
   skip_cleanup: true 
   on:
     tags: true
